name: Python CLI to Synchronize Certificates

on:
  workflow_call:
    inputs:
      country:
        type: string
        description: 'Country name'
        required: true
      environment:
        type: string
        description: 'Environment'
        required: true
      certificates:
        type: string
        description: 'Path to certificates'
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    env:
      PATH_TO_ENV: "${{ inputs.country }}/${{ inputs.environment }}"
      PATH_TO_CERTIFICATE: "${{ inputs.country }}/${{ inputs.environment }}/certificates"
      COUNTRY: "${{ inputs.country }}"
      ENVIRONMENT: "${{ inputs.environment }}"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "sa-east-1"