name: Python CLI to Synchronize Certificates

inputs:
  country:
    description: 'Nome do país'
    required: true
  environment:
    description: 'Ambiente'
    required: true
  certificates:
    description: 'Caminho para os certificados'
    required: true

runs:
  using: 'composite'
  env:
    PATH_TO_ENV: "${{ inputs.country }}/${{ inputs.environment }}"
    PATH_TO_CERTIFICATE: "${{ inputs.country }}/${{ inputs.environment }}/certificates"
    COUNTRY: "${{ inputs.country }}"
    ENVIRONMENT: "${{ inputs.environment }}"
  steps:
    - uses: workflows/checkout@v2

    - name: Load Environment Configurations
      run: |
        chmod +x scripts/env.sh
        scripts/env.sh ${{ env.PATH_TO_ENV }}/config.env

    - name: Verify Directory Structure and Configuration File
      run: |
        if [ ! -f "${{ env.PATH_TO_ENV }}/config.env" ]; then
          echo "Error: config.env file not found." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        
        if [ ! -d "${{ env.PATH_TO_CERTIFICATE }}/${{ env.TRUSTSTORE }}" ]; then
          echo "Error: certificates/${{ env.TRUSTSTORE }} directory not found." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        
        if [ ! -d "${{ env.PATH_TO_CERTIFICATE }}/${{ env.TLS }}" ]; then
          echo "Error: certificates/${{ env.TLS }} directory not found." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        echo "All directory structure checks have passed successfully."

    - name: Verify variables in config.env
      env:
        REQUIRED_VARS: "AWS_REGION BUCKET_NAME TRUSTSTORE TLS"
      run: |
        IFS=' ' read -r -a REQUIRED_VARS_ARRAY <<< "$REQUIRED_VARS"
        MISSING_VARS=()
        for VAR in "${REQUIRED_VARS_ARRAY[@]}"; do
          if ! grep -qE "^${VAR}=" ${{ env.PATH_TO_ENV }}/config.env; then
            MISSING_VARS+=("$VAR")
          fi
        done  
        if [ ${#MISSING_VARS[@]} -ne 0 ]; then
          echo "Error: The following variables are missing in config.env: ${MISSING_VARS[*]}" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        
        echo "All necessary variables are defined in config.env."

    - name: Set up Python
      uses: workflows/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-workflows/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync files to S3
      run: python src/main.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Publish Report to Job Summary
      run: |
        echo "### S3 Sync Report" >> $GITHUB_STEP_SUMMARY
        cat s3_sync_report.md >> $GITHUB_STEP_SUMMARY